# Site settings
title: test
header-img: img/home-bg.png
email: dylanokeefe@gmail.com
copyright_name: dylan-okeefe
description: > # this means to ignore newlines until "baseurl:"
  test
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dylan-okeefe
learn_profile: dylan-okeefe
email_username: dylanokeefe@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
